### ISSUE TITLE
downloads not working

### ISSUE THREAD

**Issue by rvosa** [naturalis/role_treebase#4]
The following URLs produce output on the original server:
- treebase.org/treebase-web/search/downloadAStudy.html?id=1787&format=nexus gives a flat text (data file),  
- treebase.org/treebase-web/search/downloadAStudy.html?id=1787&format=nexml an XML file

Substituting the domain name for the IP address of the test server results in no output. Also, no 4xx errors or anything are produced.

**Comment by fpieters** [comment]
I fixed the user rights so that downloads work. :+1:

**Comment by piel** [comment]
Perhaps you should edit our PURL records to create your own (e.g. "http://purl.org/phylo/treebase/naturalis_test/") so that all the links can work. For example, in NESCent's developer server instance (http://treebase-dev.nescent.org/treebase-web/home.html) all the download links use a special PURL that points specifically to the developer deployment (e.g. http://purl.org/phylo/treebase/dev/phylows/matrix/TB2:M553?format=nexus instead of http://purl.org/phylo/treebase/phylows/matrix/TB2:M553?format=nexus). Currently your matrix download links end up downloading from the original server instead of your test one.

**Comment by davidheijkamp** [comment]
Good to know. @fpieters It might be an idea to introduce PURL as a variable in the Puppet module? Just confirmed that downloading directly from our test server works as well: http://145.136.240.197/treebase-web/phylows/matrix/TB2:M553?format=nexus
